language: python

python:
    - "2.6"
    - "2.7"
    - "3.4"

env:
  - TOX_ENV=django16
  - TOX_ENV=django17
  - TOX_ENV=django18
  - TOX_ENV=coverage

install:
  - pip install tox 

script:
  - tox -e $TOX_ENV

matrix:
  exclude:
   - python: "2.6"
     env: TOX_ENV=django17
   - python: "2.6"
     env: TOX_ENV=django18
   - python: "2.6"
     env: TOX_ENV=coverage
   - python: "2.7"
     env: TOX_ENV=coverage
