# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-15 15:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('happenings', '0002_auto_20160815_1139'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='driver',
            field=models.CharField(blank=True, choices=[('Driver 1', 'Driver 1'), ('Driver 2', 'Driver 2'), ('Driver 3', 'Driver 3'), ('Driver 4', 'Driver 4'), ('Driver 5', 'Driver 5'), ('Driver 6', 'Driver 6'), ('Driver 7', 'Driver 7')], max_length=15, verbose_name='drivers'),
        ),
    ]
